### ISSUE TITLE
run_app.sh file is missing

### ISSUE THREAD

**Issue by mjena** [rwth-ti/gr-ofdm#3]
As per the README file, apps folder should have a run_app.sh file, but its missing in the GitHub code.
can you please add the file or let us know the alternative file for this?

**Comment by johschmitz** [comment]
I am traveling right now. When I get home I can check the README.
Meanwhile try run_benchmark_gui.sh, run_usrp_rx_gui.sh and run_usrp_tx_gui.sh.
