### ISSUE TITLE
ImportError on grc files

### ISSUE THREAD

**Issue by rklq1917** [rwth-ti/gr-ofdm#5]
Hello,

I have issues with all the grc files in the apps folder. When I execute a flowgraph I have the error : 
ImportError: No module named fbmc_insert_preamble_vcvc

**Comment by johschmitz** [comment]
Okay I guess we should remove the FBMC related GRC files. I don't think we ever fully implemented the GRC  part. Also the FBMC implementation in general is very experimental. If you are not particularly looking for this but rather want to run only OFDM then try removing all those GRC files.
