### ISSUE TITLE
Errors in installing ITPP

### ISSUE THREAD

**Issue by V18006** [rwth-ti/gr-ofdm#6]
Dear Sir or Madam,
I am new to gnu radio and this is my first example on implementing a full scale tutorial.
I have installed all the prerequisites as suggested, but there is an error in ITPP installation. I have followed all the steps as described in Source forge but still I am unable to resolve this `issue.
![eaitpp](https://user-images.githubusercontent.com/47884177/53231286-972c8f00-36ae-11e9-9d83-bd860a3a28c8.png)
![ebofitpp](https://user-images.githubusercontent.com/47884177/53231287-97c52580-36ae-11e9-9339-33a7a224756e.png)

**Comment by johschmitz** [comment]
Try to install ITPP (and the other dependencies) using the standard Ubuntu
software sources / package manager. No need to build the dependencies
yourself. Package should be libitpp-dev if I remember correctly.

Also in the zeromq case go for the libzmq3-dev package and python-zmq.

**Comment by V18006** [comment]
Yes, sir. You are absolutely correct. I have used 
sudo apt install libitpp-dev
Generating is also done 
Thank you sir,
Will contact if I have further queries or doubts!!
